name: Qase Tests
on:
  push:
    branches:
      - takuya-105789300606328  # Replace with the name of your non-default branch
  workflow_dispatch:

env:
  QASE_API_BASE_URL: "https://api.qase.io/v1/"
  QASE_TESTOPS_PROJECT: 'QD'
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create a Qase test run
      uses: qase-tms/gh-actions/run-create
      id: qase-run-create
      with:
        token: ${{ secrets.QASE_API_TOKEN }}
        project: ${{ env.QASE_TESTOPS_PROJECT }}
        title: Automated run - Playwright demo
        description: |
          Test Run Description
          Use multiline text and [markdown formatting](https://example.com)

    - name: Link Qase Run
      uses: cskmnrpt/qase-link-run@v2
      with:
        QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
        QASE_TESTOPS_RUN_ID: ${{ steps.qase-run-create.outputs.id }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # specify your Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Run Playwright Tests
      run: npx playwright test tests/*
