name: Qase Tests

on:
  push:
    branches:
      - takuya-105789300606328  # Replace with the name of your non-default branch
  workflow_dispatch:

env:
  QASE_API_BASE_URL: "https://api.qase.io/v1/"
  QASE_TESTOPS_PROJECT: 'QD'
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:
  qase-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the version of Node.js you need

    - name: Install dependencies
      run: npm install

    - name: Create a Qase test run
      uses: qase-tms/gh-actions/run-create@v1
      id: qase-run-create
      with:
        token: ${{ secrets.QASE_API_TOKEN }}
        project: ${{ env.QASE_TESTOPS_PROJECT }}
        title: Test Run Title
        description: |
          Test Run Description
          Use multiline text and [markdown formatting](https://example.com)

    - name: Run tests
      env:
        QASE_TESTOPS_PROJECT: ${{ env.QASE_TESTOPS_PROJECT }}
        QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
        QASE_TESTOPS_RUN_ID: ${{ steps.qase-run-create.outputs.id }}
      run: npx playwright test test/*

    - name: Complete a Qase test run
      uses: qase-tms/gh-actions/run-complete@v1
      id: complete
      if: always() && steps.qase-run-create.result == 'success'
      with:
        token: ${{ secrets.QASE_API_TOKEN }}
        project: ${{ env.QASE_TESTOPS_PROJECT }}
        id: ${{ steps.qase-run-create.outputs.id }}
